> View(pjM[grep("Clapton", pjM$artist),])
> View(pjM[grep("Clapton", pjM$album),])
> 
    > View(pjM[grep("Depeche", pjM$artist),])
> View(pjM[grep("Janet", pjM$artist),])
> View(pjM[grep("Loaf", pjM$artist),])
> View(wnoM[grep("Chains", wnoM$artist),])
> View(pjM[grep("Pantera", pjM$artist),])
> View(pjM[grep("Boyz", pjM$artist),])
> View(pjM[grep("Halen", pjM$artist),])
> View(pjM[grep("2Pac", pjM$artist),])
> View(pjM[grep("Bone", pjM$artist),])
> View(pjM[grep("Kelly", pjM$artist),])
> View(lookAtEm[2001:3000,])
> View(pjM[grep("Beatles", pjM$artist),])
> View(pjM[grep("nas", pjM$artist),])
> View(pjM[pjM$year=="1994",])
> View(pjM[grep("Nas", pjM$artist),])
> View(pjM[grep("pac", pjM$artist),])
> View(pjM[grep("as", pjM$artist),])
> View(pjM[grep("2", pjM$artist),])
> View(pjM[grep("Nas", pjM$artist, ignore.case=T),])
> View(pjM[grep("quest", pjM$artist, ignore.case=T),])
> View(pjM[grep("pearl", pjM$artist, ignore.case=T),])
> View(pjM[grep("wu", pjM$artist, ignore.case=T),])
> View(pjM[grep("doubt", pjM$artist, ignore.case=T),])
> View(pjM[grep("strait", pjM$artist, ignore.case=T),])
> View(pjM[grep("puff", pjM$artist, ignore.case=T),])
> View(pjM[grep("master", pjM$artist, ignore.case=T),])
> View(pjM[grep("leann", pjM$artist, ignore.case=T),])
> View(pjM[grep("mase", pjM$artist, ignore.case=T),])
> View(pjM[grep("dmx", pjM$artist, ignore.case=T),])
> View(pjM[grep("dog", pjM$artist, ignore.case=T),])
> View(pjM[grep("mystikal", pjM$artist, ignore.case=T),])
> View(pjM[grep("dave", pjM$artist, ignore.case=T),])
> View(pjM[grep("tool", pjM$artist, ignore.case=T),])
> View(pjM[grep("india", pjM$artist, ignore.case=T),])
> View(pjM[grep("chili", pjM$artist, ignore.case=T),])
> View(pjM[grep("whitney", pjM$artist, ignore.case=T),])
> View(pjM[grep("katy", pjM$artist, ignore.case=T),])
> View(pjM[grep("queen", pjM$artist, ignore.case=T),])
> View(pjM[grep("zac", pjM$artist, ignore.case=T),]) # or reba, or alan jackson...
> View(pjM[grep("cole", pjM$artist, ignore.case=T),])
> View(pjM[grep("schoolboy q", pjM$artist, ignore.case=T),])
